apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cups-server
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    chart: cups-server
    helm:
      values: |
        controller:
          # Disable - init container image not ARM compatible
          replicas: 0
        nodeSelector:
          dstack.uk/printer: "true"
        persistence:
          config:
            size: 100Mb
    repoURL: https://charts.truecharts.org/
    targetRevision: 1.0.29
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
