apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    chart: longhorn
    helm:
      values: |
        persistence:
          defaultClassReplicaCount: 1
    repoURL: https://charts.longhorn.io
    targetRevision: 1.2.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
