apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unifi
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    chart: unifi
    helm:
      values: |
        persistence:
          data:
            enabled: true
            type: pvc
            mountPath: /unifi
            accessMode: ReadWriteOnce
            size: 1Gi
            retain: true
        ingress:
          main:
            enabled: true
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    repoURL: https://k8s-at-home.com/charts/
    targetRevision: 5.0.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
